-- railway.DOMINIO definition

CREATE TABLE `DOMINIO` (
  `IDDOMINIO` varchar(150) NOT NULL,
  `NOMBREPAGINA` varchar(150) NOT NULL,
  `PRECIODOMINIO` decimal(10,2) NOT NULL,
  `OCUPADO` tinyint(1) NOT NULL,
  PRIMARY KEY (`IDDOMINIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.ESTADOCARRITO definition

CREATE TABLE `ESTADOCARRITO` (
  `IDESTADOCARRITO` varchar(3) NOT NULL,
  `NOMESTADOCARRITO` varchar(30) NOT NULL,
  PRIMARY KEY (`IDESTADOCARRITO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.INFOPAQUETEHOSTING definition

CREATE TABLE `INFOPAQUETEHOSTING` (
  `IDINFOPAQUETEHOSTING` int NOT NULL AUTO_INCREMENT,
  `CANTIDADSITIOS` decimal(4,0) NOT NULL,
  `NOMBREPAQUETEHOSTING` varchar(20) NOT NULL,
  `BD` decimal(4,0) NOT NULL,
  `GBENSSD` decimal(4,0) NOT NULL,
  `CORREOS` decimal(3,0) NOT NULL,
  `CERTIFICADOSSSLHTTPS` decimal(3,0) NOT NULL,
  PRIMARY KEY (`IDINFOPAQUETEHOSTING`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.PAIS definition

CREATE TABLE `PAIS` (
  `IDPAIS` decimal(3,0) NOT NULL,
  `NOMBREPAIS` varchar(15) NOT NULL,
  PRIMARY KEY (`IDPAIS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.PERIODICIDAD definition

CREATE TABLE `PERIODICIDAD` (
  `IDPERIODICIDAD` int NOT NULL AUTO_INCREMENT,
  `NOMBREPERIODICIDAD` varchar(15) NOT NULL,
  PRIMARY KEY (`IDPERIODICIDAD`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.PLAN definition

CREATE TABLE `PLAN` (
  `IDPLAN` int NOT NULL,
  `NOMBREPLAN` varchar(15) NOT NULL,
  `COMISION` decimal(10,2) NOT NULL,
  `LIMITEDOMINIOS` int NOT NULL,
  PRIMARY KEY (`IDPLAN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.TIPOCUENTA definition

CREATE TABLE `TIPOCUENTA` (
  `IDTIPOCUENTA` int NOT NULL AUTO_INCREMENT,
  `NOMBRETIPO` varchar(30) NOT NULL,
  PRIMARY KEY (`IDTIPOCUENTA`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.TIPOMETODOPAGO definition

CREATE TABLE `TIPOMETODOPAGO` (
  `IDTIPOMETODOPAGO` decimal(2,0) NOT NULL,
  `NOMBRETIPOMETODOPAGO` varchar(15) NOT NULL,
  PRIMARY KEY (`IDTIPOMETODOPAGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.TIPOTARJETA definition

CREATE TABLE `TIPOTARJETA` (
  `IDTIPOTARJETA` decimal(2,0) NOT NULL,
  `NOMBRETIPOTARJETA` varchar(15) NOT NULL,
  PRIMARY KEY (`IDTIPOTARJETA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.TRADUCCIONES definition

CREATE TABLE `TRADUCCIONES` (
  `IDTRADUCCION` int NOT NULL AUTO_INCREMENT,
  `IDIOMA` varchar(5) NOT NULL,
  `CLAVE` varchar(100) NOT NULL,
  `VALOR` text NOT NULL,
  PRIMARY KEY (`IDTRADUCCION`),
  UNIQUE KEY `IDIOMA` (`IDIOMA`,`CLAVE`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.CUENTA definition

CREATE TABLE `CUENTA` (
  `IDCUENTA` varchar(15) NOT NULL,
  `IDTIPOCUENTA` int NOT NULL,
  `IDPAIS` decimal(3,0) NOT NULL,
  `IDPLAN` int DEFAULT NULL,
  `PASSWORD` varchar(1084) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `IDENTIFICACION` varchar(15) NOT NULL,
  `NOMBRECUENTA` varchar(150) NOT NULL,
  `CORREO` varchar(50) NOT NULL,
  `TELEFONO` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FECHAREGISTRO` date NOT NULL,
  `DIRECCION` varchar(30) DEFAULT NULL,
  `TOKEN` varchar(1084) NOT NULL,
  PRIMARY KEY (`IDCUENTA`),
  UNIQUE KEY `CUENTA_CORREO_IDX` (`CORREO`) USING BTREE,
  UNIQUE KEY `CUENTA_IDENTIFICACION_IDX` (`IDENTIFICACION`) USING BTREE,
  KEY `FK_PAIS_CLIENTE` (`IDPAIS`),
  KEY `FK_TIPO_CUENTA` (`IDTIPOCUENTA`),
  KEY `FK_PLAN_CUENTA` (`IDPLAN`),
  CONSTRAINT `FK_PAIS_CLIENTE` FOREIGN KEY (`IDPAIS`) REFERENCES `PAIS` (`IDPAIS`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PLAN_CUENTA` FOREIGN KEY (`IDPLAN`) REFERENCES `PLAN` (`IDPLAN`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_TIPO_CUENTA` FOREIGN KEY (`IDTIPOCUENTA`) REFERENCES `TIPOCUENTA` (`IDTIPOCUENTA`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.PAQUETEHOSTING definition

CREATE TABLE `PAQUETEHOSTING` (
  `IDPAQUETEHOSTING` int NOT NULL AUTO_INCREMENT,
  `IDINFOPAQUETEHOSTING` int NOT NULL,
  `PRECIOPAQUETE` decimal(10,0) NOT NULL,
  `PERIODICIDAD` varchar(100) NOT NULL,
  PRIMARY KEY (`IDPAQUETEHOSTING`),
  KEY `FK_INFO_PAQUETE` (`IDINFOPAQUETEHOSTING`),
  CONSTRAINT `FK_INFO_PAQUETE` FOREIGN KEY (`IDINFOPAQUETEHOSTING`) REFERENCES `INFOPAQUETEHOSTING` (`IDINFOPAQUETEHOSTING`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.TARJETA definition

CREATE TABLE `TARJETA` (
  `IDTARJETA` int NOT NULL AUTO_INCREMENT,
  `IDTIPOTARJETA` decimal(2,0) NOT NULL,
  `NUMEROTARJETA` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CCV` varchar(255) NOT NULL,
  `FECHAVTO` date NOT NULL,
  PRIMARY KEY (`IDTARJETA`),
  UNIQUE KEY `TARJETA_NUMEROTARJETA_IDX` (`NUMEROTARJETA`) USING BTREE,
  KEY `FK_TIPOTARJETA_TARJETA` (`IDTIPOTARJETA`),
  CONSTRAINT `FK_TIPOTARJETA_TARJETA` FOREIGN KEY (`IDTIPOTARJETA`) REFERENCES `TIPOTARJETA` (`IDTIPOTARJETA`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=687 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.TICKET definition

CREATE TABLE `TICKET` (
  `IDTICKET` int NOT NULL AUTO_INCREMENT,
  `IDCLIENTE` varchar(15) NOT NULL,
  `DESCRTICKET` varchar(1084) NOT NULL,
  `NIVEL` int NOT NULL DEFAULT '1',
  `FCHCREACION` date NOT NULL,
  `ESTADOTICKET` tinyint(1) NOT NULL DEFAULT '1',
  `FCHSOLUCION` date DEFAULT NULL,
  `IDEMPLEADO` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`IDTICKET`),
  KEY `FK_CLIENTE_TICKET` (`IDCLIENTE`),
  KEY `FK_TICKET_EMPLEADO` (`IDEMPLEADO`),
  CONSTRAINT `FK_CLIENTE_TICKET` FOREIGN KEY (`IDCLIENTE`) REFERENCES `CUENTA` (`IDCUENTA`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_TICKET_EMPLEADO` FOREIGN KEY (`IDEMPLEADO`) REFERENCES `CUENTA` (`IDCUENTA`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.METODOPAGOCUENTA definition

CREATE TABLE `METODOPAGOCUENTA` (
  `IDMETODOPAGOCUENTA` int NOT NULL AUTO_INCREMENT,
  `IDTARJETA` int DEFAULT NULL,
  `IDTIPOMETODOPAGO` decimal(2,0) NOT NULL DEFAULT '0',
  `ACTIVOMETODOPAGOCUENTA` tinyint(1) NOT NULL,
  `IDCUENTA` varchar(15) NOT NULL,
  PRIMARY KEY (`IDMETODOPAGOCUENTA`),
  UNIQUE KEY `unique_metodopagocuenta` (`IDMETODOPAGOCUENTA`),
  KEY `FK_TIPOPAGO_CUENTA` (`IDTIPOMETODOPAGO`),
  KEY `FK_TARJETA_METODOPAGO` (`IDTARJETA`),
  KEY `METODOPAGOCUENTA_CUENTA_FK` (`IDCUENTA`),
  CONSTRAINT `FK_TARJETA_METODOPAGO` FOREIGN KEY (`IDTARJETA`) REFERENCES `TARJETA` (`IDTARJETA`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_TIPOPAGO_CUENTA` FOREIGN KEY (`IDTIPOMETODOPAGO`) REFERENCES `TIPOMETODOPAGO` (`IDTIPOMETODOPAGO`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `METODOPAGOCUENTA_CUENTA_FK` FOREIGN KEY (`IDCUENTA`) REFERENCES `CUENTA` (`IDCUENTA`)
) ENGINE=InnoDB AUTO_INCREMENT=1111111327 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.RESPUESTATICKET definition

CREATE TABLE `RESPUESTATICKET` (
  `IDRESPUESTATICKET` int NOT NULL AUTO_INCREMENT,
  `RESPUESTA` text NOT NULL,
  `IDTICKET` int NOT NULL,
  `FechaRespuesta` date NOT NULL,
  PRIMARY KEY (`IDRESPUESTATICKET`),
  KEY `IDTICKET` (`IDTICKET`),
  CONSTRAINT `RESPUESTATICKET_ibfk_1` FOREIGN KEY (`IDTICKET`) REFERENCES `TICKET` (`IDTICKET`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.CARRITO definition

CREATE TABLE `CARRITO` (
  `IDCARRITO` int NOT NULL AUTO_INCREMENT,
  `IDESTADOCARRITO` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '0',
  `IDCUENTA` varchar(15) NOT NULL,
  `IDMETODOPAGOCUENTA` int NOT NULL,
  PRIMARY KEY (`IDCARRITO`),
  KEY `FK_ESTADO_CARRITO` (`IDESTADOCARRITO`),
  KEY `CARRITO_METODOPAGOCUENTA_FK` (`IDMETODOPAGOCUENTA`),
  CONSTRAINT `CARRITO_METODOPAGOCUENTA_FK` FOREIGN KEY (`IDMETODOPAGOCUENTA`) REFERENCES `METODOPAGOCUENTA` (`IDMETODOPAGOCUENTA`),
  CONSTRAINT `FK_ESTADO_CARRITO` FOREIGN KEY (`IDESTADOCARRITO`) REFERENCES `ESTADOCARRITO` (`IDESTADOCARRITO`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=198 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.CARRITODOMINIO definition

CREATE TABLE `CARRITODOMINIO` (
  `IDDOMINIO` varchar(150) NOT NULL,
  `IDCARRITO` int NOT NULL,
  `IDCARRITODOMINIO` varchar(10) NOT NULL,
  PRIMARY KEY (`IDDOMINIO`,`IDCARRITO`,`IDCARRITODOMINIO`),
  KEY `FK_CARRITO_DOMINIO` (`IDCARRITO`),
  CONSTRAINT `FK_CARRITO_DOMINIO` FOREIGN KEY (`IDCARRITO`) REFERENCES `CARRITO` (`IDCARRITO`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_DOMINIO_CARRITO` FOREIGN KEY (`IDDOMINIO`) REFERENCES `DOMINIO` (`IDDOMINIO`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.FACTURA definition

CREATE TABLE `FACTURA` (
  `IDFACTURA` int NOT NULL AUTO_INCREMENT,
  `IDCARRITO` int NOT NULL,
  `PAGOFACTURA` date NOT NULL,
  `VIGFACTURA` date NOT NULL,
  `VALORFC` decimal(10,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`IDFACTURA`),
  UNIQUE KEY `FK_CARRITO_FACTURA` (`IDCARRITO`) USING BTREE,
  CONSTRAINT `FK_CARRITO_FACTURA` FOREIGN KEY (`IDCARRITO`) REFERENCES `CARRITO` (`IDCARRITO`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.FACTURAPAQUETE definition

CREATE TABLE `FACTURAPAQUETE` (
  `IDFACTURAPAQUETE` int NOT NULL AUTO_INCREMENT,
  `IDMETODOPAGOCUENTA` int NOT NULL,
  `IDPAQUETEHOSTING` int DEFAULT NULL,
  `FCHPAGO` date NOT NULL,
  `FCHVENCIMIENTO` date NOT NULL,
  `ESTADO` int NOT NULL,
  `VALORFP` decimal(10,0) NOT NULL,
  PRIMARY KEY (`IDFACTURAPAQUETE`),
  KEY `FK_FCT_PQT_CUENTA` (`IDMETODOPAGOCUENTA`),
  KEY `FK_PAQUETE_FCT` (`IDPAQUETEHOSTING`),
  CONSTRAINT `FK_FCT_PQT_CUENTA` FOREIGN KEY (`IDMETODOPAGOCUENTA`) REFERENCES `METODOPAGOCUENTA` (`IDMETODOPAGOCUENTA`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_PAQUETE_FCT` FOREIGN KEY (`IDPAQUETEHOSTING`) REFERENCES `PAQUETEHOSTING` (`IDPAQUETEHOSTING`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- railway.ITEMPAQUETE definition

CREATE TABLE `ITEMPAQUETE` (
  `IDREGITEMPAQUETE` int NOT NULL AUTO_INCREMENT,
  `IDFACTURAPAQUETE` int NOT NULL,
  `DESCRIPCION` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `TAMANO` varchar(10) NOT NULL,
  `NOMBREITEM` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`IDREGITEMPAQUETE`),
  KEY `FK_FACT_ALMC` (`IDFACTURAPAQUETE`),
  CONSTRAINT `FK_FACT_ALMC` FOREIGN KEY (`IDFACTURAPAQUETE`) REFERENCES `FACTURAPAQUETE` (`IDFACTURAPAQUETE`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=934 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
