INSERT INTO railway.ESTADOCARRITO (IDESTADOCARRITO,NOMESTADOCARRITO) VALUES
	 ('0','VACIO'),
	 ('1','EN PROCESO'),
	 ('2','FACTURADO'),
	 ('3','TRANSFERIDO');
INSERT INTO railway.INFOPAQUETEHOSTING (CANTIDADSITIOS,NOMBREPAQUETEHOSTING,BD,GBENSSD,CORREOS,CERTIFICADOSSSLHTTPS) VALUES
	 (10,'CHIBCHA-TEST',10,10,10,10),
	 (2,'Plata',2,10,2,1),
	 (2,'Plata',2,10,2,1),
	 (2,'Plata',2,10,2,1),
	 (3,'Platino',3,30,3,2),
	 (3,'Platino',3,30,3,2),
	 (3,'Platino',3,30,3,2),
	 (5,'Oro',5,80,5,3),
	 (5,'Oro',5,80,5,3),
	 (5,'Oro',5,80,5,3);
INSERT INTO railway.PAIS (IDPAIS,NOMBREPAIS) VALUES
	 (76,'BRASIL'),
	 (170,'COLOMBIA'),
	 (218,'ECUADOR'),
	 (604,'PER�'),
	 (862,'VENEZUELA');
INSERT INTO railway.PAQUETEHOSTING (IDINFOPAQUETEHOSTING,PRECIOPAQUETE,PERIODICIDAD) VALUES
	 (20,10,'30'),
	 (21,30,'180'),
	 (22,90,'365'),
	 (23,20,'30'),
	 (24,60,'180'),
	 (25,120,'365'),
	 (26,54,'30'),
	 (27,140,'180'),
	 (28,300,'365');
INSERT INTO railway.PLAN (IDPLAN,NOMBREPLAN,COMISION,LIMITEDOMINIOS) VALUES
	 (0,'Sin plan',0.00,0),
	 (1,'Basico',21.00,32),
	 (2,'Premium',98.00,21);
INSERT INTO railway.TIPOCUENTA (NOMBRETIPO) VALUES
	 ('CLIENTE'),
	 ('DISTRIBUIDOR'),
	 ('ADMIN'),
	 ('EMPLEADO'),
	 ('POSTULADO'),
	 ('ELIMINADA'),
	 ('INHABILITADO'),
	 ('COORDINADOR NIVEL 1'),
	 ('COORDINADOR NIVEL 2'),
	 ('COORDINADOR NIVEL 3');
INSERT INTO railway.TIPOCUENTA (NOMBRETIPO) VALUES
	 ('TECNICO NIVEL 1'),
	 ('TECNICO NIVEL 2'),
	 ('TECNICO NIVEL 3');
INSERT INTO railway.TIPOMETODOPAGO (IDTIPOMETODOPAGO,NOMBRETIPOMETODOPAGO) VALUES
	 (0,'SIN MÉTODO'),
	 (1,'TARJETA'),
	 (2,'PSE');
INSERT INTO railway.TIPOTARJETA (IDTIPOTARJETA,NOMBRETIPOTARJETA) VALUES
	 (1,'VISA'),
	 (2,'MASTERCARD'),
	 (3,'DINERS'),
	 (4,'AMEX'),
	 (5,'DISCOVER');
INSERT INTO railway.TRADUCCIONES (IDIOMA,CLAVE,VALOR) VALUES
	 ('ES','welcome_message','Bienvenidos A LEAGUE OFLEGENDSS'),
	 ('ES','welcome_messages','Bienvenidos A LEAGUE OFLEGENDSS');
